[solution]
name = "<placeholder>"      # Solution name, injected at runtime based on algorithm
definition = "<placeholder>"  # Injected at runtime based on --definition flag
author = "lmu-css"                # Team/author name

[build]
language = "triton"               # triton | cuda
entry_point = "<placeholder>"     # Kernel function name, injected at runtime based on algorithm
